name: DailyRewardsPE
version: 1.0.0
author: Terpz710
api: [5.0.0]
main: Terpz710\DailyRewardsPE\Main
description: The original DailyRewardsPE plugin for Pocketmine-MP.

permissions:
  dailyrewardspe.command.daily:
    description: Daily Rewards.
    default: true
  dailyrewardspe.command.weekly:
    description: Weekly Rewards.
    default: true
  dailyrewardspe.command.monthly:
    description: Monthly Rewards.
    default: true
